services:
  dagster-dagit:
    build: .
    ports:
      - 3333:3333
  dagster-daemon:
    build: .
    command: "dagster-daemon run"
  dagster-postgres:
    image: postgres:13.3
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - dagster-postgres:/var/lib/postgresql/data
  prometheus-push:
    image: prom/pushgateway
    ports: 
      - 9091:9091
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
volumes:
  dagster-postgres:
    driver: local
